version: "3"

services:
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  next:
    build: .
    image: next-news-app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

volumes:
  cache:
    driver: local
