name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      ARTIFACT_NAME: ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.event.repository.updated_at }}.zip
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Zip artifact
        run: zip ${{ env.ARTIFACT_NAME }} ./* -r
      - run: mkdir artifacts && mv ./${{ env.ARTIFACT_NAME }} ./artifacts/${{ env.ARTIFACT_NAME }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2
      - name: Deploy
        run: aws s3 sync ./artifacts s3://csmm-built-artifacts
